name: Trigger auto deployment for ese-tola-nodejs-example

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ese-tola-nodejs-example-AutoDeployTrigger-93f26e76-74a6-4379-b7dd-d4548155c070.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ESETOLANODEJSEXAMPLE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ESETOLANODEJSEXAMPLE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ESETOLANODEJSEXAMPLE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.ESETOLANODEJSEXAMPLE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ESETOLANODEJSEXAMPLE_REGISTRY_PASSWORD }}
          containerAppName: ese-tola-nodejs-example
          resourceGroup: ese-tola-kyle-taylor
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


