name: Build & Publish Container

on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*" # e.g. v1.2.3
  pull_request:

permissions:
  contents: read
  packages: write # needed to push to ghcr.io

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # owner/repo (metadata action will lowercase)

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU (for multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=sha-,format=short
            # Add 'latest' only on default branch
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.description=Datadog Node.js init tracer sample app
            org.opencontainers.image.title=datadog-nodejs-init-tracer

      - name: Determine DD_VERSION
        id: version
        shell: bash
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "val=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          else
            echo "val=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build (and push if not PR)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            DD_SERVICE=datadog-nodejs-init-tracer
            DD_ENV=local
            DD_VERSION=${{ steps.version.outputs.val }}
            DD_SITE=datadoghq.com
